[tools]
starship = "latest"
ripgrep = "latest"
bat = "latest"
cilium-cli = "latest"
helm = "latest"
cosign = "latest"
gcloud = "latest"
awscli = { version = "latest", symlink_bins = "true" }

[settings]
experimental = true
