[tools]
starship = "latest"
ripgrep = "latest"
bat = "latest"
cilium-cli = "latest"
helm = "latest"
cosign = "latest"
gh = "latest"
k9s = "latest"
neovim = "latest"
fd = "latest"
lazygit = "latest"

[settings]
experimental = true
